server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 128
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbms?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages/
    suffix: .html
mybatis:
  mapper-locations:
  - classpath:/mapper/*/*.xml
logging:
  level:
    com.cy: debug